---
# tasks file for ssh

- name: Configuration sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'

- name: Vérification de la présence du répertoire .ssh
  stat: 
    path: /home/{{ users_name }}/.ssh
  register: ssh_result_ssh_folder

- name: Création du répertoire .ssh
  file: 
    path: /home/{{ users_name }}/.ssh 
    state: directory 
    owner: '{{ users_name }}'
    group: '{{ users_group }}' 
    mode: '0755'
  when: ssh_result_ssh_folder.stat.exists == false

- name: Configuration de la clé authorisé
  template:
    src: authorized_keys.j2
    dest: /home/{{ users_name }}/.ssh/authorized_keys
    owner: "{{ users_name }}"
    group: "{{ users_group }}"
    mode: '0644'

...